# Generated by Django 2.1.4 on 2019-01-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(max_length=14),
        ),
    ]
