# Generated by Django 2.1.4 on 2019-01-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_employeededuction_employeeearning_taxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeJops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Employee')),
            ],
        ),
    ]
