# Generated by Django 2.1.4 on 2019-01-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_employeejops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejops',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.Employee'),
        ),
    ]
