# Generated by Django 2.1.4 on 2019-01-05 18:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190105_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='martial_status',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='place_of_birth',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
