# Generated by Django 2.1.4 on 2019-01-05 18:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190105_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=django_countries.fields.CountryField(default='EG', max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=django_countries.fields.CountryField(default='EG', max_length=2),
        ),
    ]
